name: SeniorOS V2 - 鸿稀鳞绝
run-name: ${{ gitea.actor }} is testing out Gitea Actions 🚀
on: [push]

jobs:
  Explore-Gitea-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Equipping Items
        uses: actions/checkout@v3
      - run: apt-get update
      - run: apt-get install git curl wget python3 python-is-python3 python3-pip -y
      - run: pip install virtualenv --break-system-packages
      - run: cd ./esp-idf
      - run: pip install -r requirement.txt --break-system-packages
      - run: sudo ./install.sh
      - name: Build
        uses: actions/checkout@v3
      - run: echo "💡 The ${{ gitea.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        uses: actions/checkout@v3
        run: |
          ls ${{ gitea.workspace }}                    
      - run: echo "🍏 This job's status is ${{ job.status }}."
